---
abstract: 'use Bread::Board to configure your Catalyst app'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::View::TT: 0
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.21
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Bread-Board
no_index:
  directory:
    - inc
    - t
requires:
  Bread::Board: 0.13
  Catalyst: 0
  Moose: 1.00
  MooseX::Types::Path::Class: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
